// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGcfoRXjswk0LZl7u9EZqGMe76EsIkRH0',
    appId: '1:567318524072:android:4e04ff7b5a1baeddde929d',
    messagingSenderId: '567318524072',
    projectId: 'panadol-93bfb',
    storageBucket: 'panadol-93bfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLcVYb6Po2cziewHmaK0Tsu4YzUZrcW0',
    appId: '1:567318524072:ios:85d6c4c8c23a840fde929d',
    messagingSenderId: '567318524072',
    projectId: 'panadol-93bfb',
    storageBucket: 'panadol-93bfb.appspot.com',
    androidClientId: '567318524072-iom7cdfla3psphgrnms36t0oh7mk3eko.apps.googleusercontent.com',
    iosClientId: '567318524072-38u9bmm4b6tem77aun3310oi87hsdbm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.panadol',
  );
}
